name: Main Comment Commands
on:
  issue_comment:
    types: [created]
env:
  terraform_version: latest
  tflint_version: latest
jobs:
  cloudTests:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Cloud Tests
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: full-ci
  reviewAndApprove:
    runs-on: ubuntu-latest
    steps:
      - name: Review and Approve
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: approve
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: merge