name: merge-command
on:
  repository_dispatch:
    types: [merge-command]
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ env.PR_NUMBER }}
          method: merge
          repo: juliangruber/octokit-action
  commentFeedback:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction on success
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
