name: merge-command
on:
  repository_dispatch:
    types: [merge-command]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ env.PULL_NUMBER }}
          method: merge
          repo: juliangruber/octokit-action
  commentFeedback:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction on success
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray