name: merge-command
on:
  repository_dispatch:
    types: [merge-command]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ github.event.client_payload.github.payload.issue.number }}
          method: merge
          repo: juliangruber/octokit-action
  commentFeedback:
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Add reaction on success
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
